[world]
name = "dominion"
description = "Dominion Poker Game powered by Dojo"
website = "https://dominion.fun/"
seed = "dominion"

[world.socials]
x = "https://x.com/dominionhub"
discord = "#"
github = "https://github.com/dominionhub"
telegram = "https://t.me/+QvEMoi3rjek5Mjdh"

[namespace]
default = "dominion"

[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
# Default account for katana with seed = 0
account_address = "0x0111e4cba299238e466c4dc38b77d79087192fafe1978295c3352c2dde258755"
private_key = "0x06e5767faed8e32ac5c6b4e03c5616cbdd9c0dc2207aff476b281a9c0dc5026d"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[init_call_args]
"dominion-table_system" = ["0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec", "0x6"]
"dominion-table_management_system" = ["0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"]
"dominion-actions_system" = ["0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"]

[writers]
"dominion" = ["dominion-actions_system", "dominion-table_system", "dominion-cashier_system", "dominion-table_management_system"]
