[world]
name = "dominion"
description = "Dominion Poker Game powered by Dojo"
website = "https://dominion.fun/"
seed = "dominion"

[world.socials]
x = "https://x.com/dominionhub"
discord = "#"
github = "https://github.com/dominionhub"
telegram = "https://t.me/+QvEMoi3rjek5Mjdh"


[env]
rpc_url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_7"
# Default account for katana with seed = 0
account_address = "0x066bd2f1eb0133996872e7a3bff507e9c9734ac872f39df8b17c735dcb7e4cab"
private_key = "..."
world_address = "0x3f73735a76cf44a357fb55f03dfaa84e0e4be53a70e73cb324aab9c3649bbf8"

[namespace]
default = "dominion"

[init_call_args]
# Add init params for constructors.

[writers]
"dominion" = ["dominion-actions_system", "dominion-cashier_system", "dominion-table_management_system"]
