[world]
name = "dominion"
description = "Dominion Poker Game powered by Dojo"
website = "https://dominion.fun/"
seed = "dominion-v16"

[world.socials]
x = "https://x.com/dominionhub"
discord = "#"
github = "https://github.com/dominionhub"
telegram = "https://t.me/+QvEMoi3rjek5Mjdh"


[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "{PUBLIC_KEY}"
private_key = "{PRIVATE_KEY}"
world_address = "0x05386d840b14c94c37cb6f03aa9908c18bc1f2a7ba2826bc3a6f52da5121117f"

[namespace]
default = "dominion"

[init_call_args]
# Add init params for constructors.

[writers]
"dominion" = ["dominion-actions_system", "dominion-cashier_system", "dominion-table_management_system"]
