[world]
name = "dominion"
description = "Dominion Poker Game powered by Dojo"
website = "https://dominion.fun/"
seed = "dominion-v16"

[world.socials]
x = "https://x.com/dominionhub"
discord = "#"
github = "https://github.com/dominionhub"
telegram = "https://t.me/+QvEMoi3rjek5Mjdh"


[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x066bd2f1eb0133996872e7a3bff507e9c9734ac872f39df8b17c735dcb7e4cab"
private_key = "0x049df87a92d2530db26d45c9c13a3881067ff7a082c81c790512fcb885cb68b0"
world_address = "0x05386d840b14c94c37cb6f03aa9908c18bc1f2a7ba2826bc3a6f52da5121117f"

[namespace]
default = "dominion"

[init_call_args]
# Add init params for constructors.

[writers]
"dominion" = ["dominion-actions_system", "dominion-cashier_system", "dominion-table_management_system"]
