[package]
name = "dominion"
version = "1.2.1"
edition = "2024_07"

[dependencies]
starknet = "2.9.2"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }
origami_random = { git = "https://github.com/dojoengine/origami.git" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
sierra = true

[dev-dependencies]
cairo_test = "2.9.2"
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo", tag = "v1.2.0" }

[profile.sepolia]
